image: node:16.5.0

pages:
  stage: deploy
  cache:
    key:
      files:
        - package-lock.json
      prefix: npm
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build
    - cp -a dist/. public/
    - cp public/index.html public/404.html  # Add this line to handle client-side routing
  artifacts:
    paths:
      - public
  when: manual
