Primary navigation
Homepage
Next

 7
 Search or go to…
Project
G
G9_SEP490_SU2024
Learn GitLab
58%

Pinned
Issues
0
Merge requests
0

Manage

Plan

Code
Merge requests
0
Repository
Branches
Commits
Tags
Repository graph
Compare revisions
Snippets
Locked files

Build

Secure

Deploy

Operate

Monitor

Analyze

Settings
MANHNC
G9_SEP490_SU2024
Repository
You pushed to 
set-sast-config-1
 43 minutes ago
g9_sep490_su2024
.gitlab-ci.yml
Son Nguyen Viet Bao's avatar
Update .gitlab-ci.yml file
Son Nguyen Viet Bao authored 1 week ago
50060c80
 Code owners
Assign users and groups as approvers for specific file changes. Learn more.
 This GitLab CI configuration is valid. Learn more
.gitlab-ci.yml
372 B
image: node:16.5.0
pages:
  stage: deploy
  cache:
    key:
      files:
        - package-lock.json
      prefix: npm
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build
    - cp -a dist/. public/
    - cp public/index.html public/404.html  # Add this line to handle client-side routing
  artifacts:
    paths:
      - public
  when: manual
