default:
  image:
    name: aikidosecurity/local-scanner:v1.0.21
    entrypoint: [""]

run_aikido_selfscanner:
  script:
  - aikido-local-scanner scan ./ --apikey $AIKIDO_LOCAL_SCANNER_TOKEN --repositoryname https://gitlab.com/manhnc2/g3_sep490_su2024 --branchname main
  rules:
    - if: $CI_COMMIT_BRANCH == "main"