const parts = [
  { text: "input: Tên dự án là gì?" },
  { text: "output: FPT University Société place" },
  { text: "input: Mục tiêu chính của dự án này là gì?" },
  { text: "output: Xây dựng một nền tảng nội bộ để kết nối sinh viên hiện tại, cựu sinh viên, giảng viên và nhân viên thông qua các hệ thống ứng dụng nội bộ của FPTU. Nền tảng này sẽ tạo điều kiện kết nối sinh viên từ các cơ sở khác nhau, tăng cường chia sẻ kiến thức trên các cơ sở của FPTU." },
  { text: "input: Các hệ thống hiện tại nào được đề cập trong báo cáo?" },
  { text: "output: Workplace (Meta), FE forum (FPTU's forum), NEU Alumni." },
  { text: "input: Các tính năng chính của sản phẩm phần mềm này là gì?" },
  { text: "output: Xác thực, Quản lý vai trò và cấp quyền, Tin nhắn/thông báo theo thời gian thực, Phản ứng/bình luận bài đăng theo thời gian thực, Tạo nhóm thành viên, Quản lý thành viên/bài đăng/nội dung, Gợi ý/tìm kiếm/hashtag thông minh, Gợi ý bài đăng với thông tin liên quan như: cơ sở, chuyên ngành, học kỳ, môn học, lớp học, chủ đề,..., Gợi ý kết bạn và nhóm với thông tin liên quan như chuyên ngành, lớp học, bạn bè chung, chủ đề quan tâm chung,..." },
  { text: "input: Những hạn chế của dự án là gì?" },
  { text: "output: Khó khăn trong việc kết nối và giao tiếp với các bên liên quan, Thời gian ngắn để hoàn thành dự án, Áp dụng công nghệ/công cụ mới để tiến hành dự án, Thiếu kinh nghiệm trong việc thực hiện phân tích yêu cầu/chức năng và truy xuất thông tin." },
  { text: "input: Tầm nhìn sản phẩm phần mềm là gì?" },
  { text: "output: Tạo ra một cộng đồng kỹ thuật số sôi động, tương tác và an toàn, cách mạng hóa cách sinh viên và nhân viên kết nối, giao tiếp và cộng tác." },
  { text: "input: Cơ hội kinh doanh của dự án này là gì?" },
  { text: "output: Giải quyết nhu cầu giao tiếp đang phát triển của các tổ chức giáo dục bằng cách cung cấp một nền tảng tập trung cho sinh viên và nhân viên kết nối, chia sẻ bài viết và cộng tác." },
  { text: "input: Các bên liên quan chính của dự án là ai?" },
  { text: "output: Giám sát dự án: Nguyễn Cường Mạnh\nNhóm dự án: Nguyễn Khải Hoàn (Leader), Bùi Quốc Anh, Nguyễn Anh Quân, Nguyễn Hồng Sơn, Lê Hải Hoàn\nCác bên liên quan khác: Phan Bảo Châu (FPT Brand)" },
  { text: "input: Báo cáo này được tạo vào tháng mấy?" },
  { text: "output: Tháng 5 năm 2024" },
  { text: "input: Trường Đại học FPT được thành lập khi nào?" },
  { text: "output: Trường Đại học FPT được thành lập ngày 8/9/2006." },
  { text: "input: Trường Đại học FPT do ai đầu tư?" },
  { text: "output: Trường Đại học FPT do Tập đoàn FPT đầu tư 100% vốn." },
  { text: "input: Trường Đại học FPT có những cơ sở đào tạo nào?" },
  { text: "output: Hà Nội:\n\nHòa Lạc campus, Khu công nghệ cao Hòa Lạc, km 29 Đại lộ Thăng Long\nTòa nhà Detech, số 8 Tôn Thất Thuyết, Mỹ Đình 2, Từ Liêm\nTòa nhà Việt-Úc Mỹ Đình 1, Nam Từ Liêm, Hà Nội\n4 cơ sở khác tại Hà Nội\nĐà Nẵng:\n\nCơ sở 137, Nguyễn Thị Thập, phường Hòa Minh, quận Liên Chiểu, TP Đà Nẵng\nFPT Campus, Khu đô thị FPT City, phường Hòa Hải, quận Ngũ Hành Sơn, TP Đà Nẵng\nBình Định:\n\nKhu đô thị An Phú Thịnh, phường Nhơn Bình, TP. Quy Nhơn, Bình Định\nThành phố Hồ Chí Minh:\n\nTòa nhà Đại học FPT, Khu Công nghệ Cao, phường Tân Phú, TP Thủ Đức, TP Hồ Chí Minh\nSố 5 Nguyễn Gia Thiều, phường Võ Thị Sáu, Quận 3, TP Hồ Chí Mình (cơ sở Viện Quản trị và Công nghệ FSB)\nCần Thơ:\n\nCầu Rau Răm, Khu vực 6, Nguyễn Văn Cừ nối dài, phường An Bình, quận Ninh Kiều, TP. Cần Thơ" },
  { text: "input: Trường Đại học FPT đã đạt được những thành tích nào?" },
  { text: "output: Chứng nhận Ba Sao QS Stars vào tháng 11/2012, trong đó tiêu chí về Chất lượng đào tạo cùng Đóng góp xã hội được đánh giá 5 sao\nViện quản trị và Công nghệ FSB được Eduniversal xếp hạng TOP#2 trường đào tạo Quản trị kinh doanh hàng đầu Việt Nam liên tiếp nhiều năm liền từ năm 2012\nChứng nhận thành viên liên kết AUN - QA vào ngày 25/03/2018" },
  { text: "input: Trường Đại học FPT có triển khai chương trình đào tạo quốc tế không?" },
  { text: "output: Có, năm 2018 trường triển khai chương trình đào tạo quốc tế tại Lào, tuyển 150 sinh viên cho 2 chương trình đào tạo quốc tế ngành Kỹ thuật phần mềm và Quản trị Kinh doanh (chuyên sâu Thương mại điện tử)." },
  { text: "input: Hiệu trưởng đầu tiên của trường Đại học FPT là ai?" },
  { text: "output: Hiệu trưởng đầu tiên của trường Đại học FPT là TS. Lê Trường Tùng." },
  { text: "input: Who is the project supervisor?" },
  { text: "output: Nguyễn Cường Mạnh" },
  { text: "input: Tên dự án là gì?" },
  { text: "output: FPT University Société place" },
  { text: "input: Mục tiêu chính của dự án này là gì?" },
  { text: "output: Xây dựng một nền tảng nội bộ để kết nối sinh viên hiện tại, cựu sinh viên, giảng viên và nhân viên thông qua các hệ thống ứng dụng nội bộ của FPTU. Nền tảng này sẽ tạo điều kiện kết nối sinh viên từ các cơ sở khác nhau, tăng cường chia sẻ kiến thức trên các cơ sở của FPTU." },
  { text: "input: Các hệ thống hiện tại nào được đề cập trong báo cáo?" },
  { text: "output: Workplace (Meta), FE forum (FPTU's forum), NEU Alumni." },
  { text: "input: Các tính năng chính của sản phẩm phần mềm này là gì?" },
  { text: "output: Xác thực, Quản lý vai trò và cấp quyền, Tin nhắn/thông báo theo thời gian thực, Phản ứng/bình luận bài đăng theo thời gian thực, Tạo nhóm thành viên, Quản lý thành viên/bài đăng/nội dung, Gợi ý/tìm kiếm/hashtag thông minh, Gợi ý bài đăng với thông tin liên quan như: cơ sở, chuyên ngành, học kỳ, môn học, lớp học, chủ đề,..., Gợi ý kết bạn và nhóm với thông tin liên quan như chuyên ngành, lớp học, bạn bè chung, chủ đề quan tâm chung,..." },
  { text: "input: Những hạn chế của dự án là gì?" },
  { text: "output: Khó khăn trong việc kết nối và giao tiếp với các bên liên quan, Thời gian ngắn để hoàn thành dự án, Áp dụng công nghệ/công cụ mới để tiến hành dự án, Thiếu kinh nghiệm trong việc thực hiện phân tích yêu cầu/chức năng và truy xuất thông tin." },
  { text: "input: Tầm nhìn sản phẩm phần mềm là gì?" },
  { text: "output: Tạo ra một cộng đồng kỹ thuật số sôi động, tương tác và an toàn, cách mạng hóa cách sinh viên và nhân viên kết nối, giao tiếp và cộng tác." },
  { text: "input: Cơ hội kinh doanh của dự án này là gì?" },
  { text: "output: Giải quyết nhu cầu giao tiếp đang phát triển của các tổ chức giáo dục bằng cách cung cấp một nền tảng tập trung cho sinh viên và nhân viên kết nối, chia sẻ bài viết và cộng tác." },
  { text: "input: Các bên liên quan chính của dự án là ai?" },
  { text: "output: Giám sát dự án: Nguyễn Cường Mạnh\nNhóm dự án: Nguyễn Khải Hoàn (Leader), Bùi Quốc Anh, Nguyễn Anh Quân, Nguyễn Hồng Sơn, Lê Hải Hoàn\nCác bên liên quan khác: Phan Bảo Châu (FPT Brand)" },
  { text: "input: Báo cáo này được tạo vào tháng mấy?" },
  { text: "output: Tháng 5 năm 2024" },
  { text: "input: Trường Đại học FPT được thành lập khi nào?" },
  { text: "output: Trường Đại học FPT được thành lập ngày 8/9/2006." },
  { text: "input: Trường Đại học FPT do ai đầu tư?" },
  { text: "output: Trường Đại học FPT do Tập đoàn FPT đầu tư 100% vốn." },
  { text: "input: Trường Đại học FPT có những cơ sở đào tạo nào?" },
  { text: "output: Hà Nội:\n\nHòa Lạc campus, Khu công nghệ cao Hòa Lạc, km 29 Đại lộ Thăng Long\nTòa nhà Detech, số 8 Tôn Thất Thuyết, Mỹ Đình 2, Từ Liêm\nTòa nhà Việt-Úc Mỹ Đình 1, Nam Từ Liêm, Hà Nội\n4 cơ sở khác tại Hà Nội\nĐà Nẵng:\n\nCơ sở 137, Nguyễn Thị Thập, phường Hòa Minh, quận Liên Chiểu, TP Đà Nẵng\nFPT Campus, Khu đô thị FPT City, phường Hòa Hải, quận Ngũ Hành Sơn, TP Đà Nẵng\nBình Định:\n\nKhu đô thị An Phú Thịnh, phường Nhơn Bình, TP. Quy Nhơn, Bình Định\nThành phố Hồ Chí Minh:\n\nTòa nhà Đại học FPT, Khu Công nghệ Cao, phường Tân Phú, TP Thủ Đức, TP Hồ Chí Minh\nSố 5 Nguyễn Gia Thiều, phường Võ Thị Sáu, Quận 3, TP Hồ Chí Mình (cơ sở Viện Quản trị và Công nghệ FSB)\nCần Thơ:\n\nCầu Rau Răm, Khu vực 6, Nguyễn Văn Cừ nối dài, phường An Bình, quận Ninh Kiều, TP. Cần Thơ" },
  { text: "input: Trường Đại học FPT đã đạt được những thành tích nào?" },
  { text: "output: Chứng nhận Ba Sao QS Stars vào tháng 11/2012, trong đó tiêu chí về Chất lượng đào tạo cùng Đóng góp xã hội được đánh giá 5 sao\nViện quản trị và Công nghệ FSB được Eduniversal xếp hạng TOP#2 trường đào tạo Quản trị kinh doanh hàng đầu Việt Nam liên tiếp nhiều năm liền từ năm 2012\nChứng nhận thành viên liên kết AUN - QA vào ngày 25/03/2018" },
  { text: "input: Trường Đại học FPT có triển khai chương trình đào tạo quốc tế không?" },
  { text: "output: Có, năm 2018 trường triển khai chương trình đào tạo quốc tế tại Lào, tuyển 150 sinh viên cho 2 chương trình đào tạo quốc tế ngành Kỹ thuật phần mềm và Quản trị Kinh doanh (chuyên sâu Thương mại điện tử)." },
  { text: "input: Hiệu trưởng đầu tiên của trường Đại học FPT là ai?" },
  { text: "output: Hiệu trưởng đầu tiên của trường Đại học FPT là TS. Lê Trường Tùng." },
  { text: "input: What is the project background?" },
  { text: "output: The platform aims to connect FPT University students, alumni, faculty, and staff to enhance communication and sharing of knowledge across campuses." },
  { text: "input: What is the main vision of the software?" },
  { text: "output: To create a vibrant, interactive, and secure digital community that revolutionizes the way students and staff connect, communicate, and collaborate." },
  { text: "input: What are some business opportunities?" },
  { text: "output: The platform can enhance the university's communication infrastructure and may serve as a model for other educational institutions, opening avenues for partnerships and licensing." },
  { text: "input: What is Workplace (Meta)?" },
  { text: "output: A business communication platform from Meta that combines chat, video, groups, and work tools in one secure environment." },
  { text: "input: What are the advantages of Workplace?" },
  { text: "output: Familiar, mobile, integrated, safe" },
  { text: "input: What are the disadvantages of Workplace?" },
  { text: "output: High price (From $4 to $8 per person/month)" },
  { text: "input: What is FE forum?" },
  { text: "output: An internal forum of FPT Education Group for users with specific email domains it is not accessible to students." },
  { text: "input: What are the main features of FE forum?" },
  { text: "output: Communication Tools, Announcement Tools" },
  { text: "input: What are the disadvantages of FE forum?" },
  { text: "output: Poor UI/UX, low system performance, insufficient features, only for staff." },
  { text: "input: What is NEU Alumni?" },
  { text: "output: A forum network for NEU alumni to connect and share knowledge with current students." },
  { text: "input: What are the disadvantages of NEU Alumni?" },
  { text: "output: Poor UI/UX, insufficient features, last posting was 5 years ago." },
  { text: "input: What are the main features of NEU Alumni?" },
  { text: "output: Communication Tools, Announcement Tools" },
  { text: "input: What features are excluded in the project?" },
  { text: "output: None specified explicitly, but limitations include difficulty in stakeholder communication, short project timeline, and lack of experience with new technologies." },
  { text: "input: What is the purpose of the platform?" },
  { text: "output: To facilitate connections among students, alumni, faculty, and staff, and to foster a collaborative environment within FPT University." },
  { text: "input: What are the key security features?" },
  { text: "output: Security and Privacy Controls, near/real-time messaging, workflow review approval reports." },
  { text: "input: What is the timeline of the first project change?" },
  { text: "output: 18/05/2024 - Creation of document, adding several sections." },
  { text: "input: What was updated on 23/05/2024?" },
  { text: "output: Update to the Existing System and Major Features sections." },
  { text: "input: What is the email of the project leader?" },
  { text: "output: hoannkhe161601@fpt.edu.vn" },
  { text: "input: What are the intended benefits of the platform?" },
  { text: "output: Enhanced communication, academic and professional development, a vibrant engaged university community." },
  { text: "input: What is the target user group for the platform?" },
  { text: "output: FPT University students, alumni, faculty, and staff." },
  { text: "input: What is the mobile number of Nguyễn Khải Hoàn?" },
  { text: "output: 967861413" },
  { text: "input: Who is responsible for updating the project document?" },
  { text: "output: Bùi Quốc Anh" },
  { text: "input: What is the role of Nguyễn Khải Hoàn?" },
  { text: "output: Leader" },
  { text: "input: What is the email of Bùi Quốc Anh?" },
  { text: "output: anhbqhe163864@fpt.edu.vn" },
  { text: "input: What was the last change made to the project document?" },
  { text: "output: Update to the Existing System and Major Features sections on 23/05/2024" },
  { text: "input: What is the name of the department of Phan Bảo Châu?" },
  { text: "output: FPT Brand" },
  { text: "input: When was FPT University established?" },
  { text: "output: FPT University was officially established on September 8, 2006." },
  { text: "input: What is special about FPT University?" },
  { text: "output: FPT University is the first university in Vietnam established by a business, with 100% investment from FPT Corporation." },
  { text: "input: What are the main training fields at FPT University?" },
  { text: "output: Information Technology, Business Administration, Communication Technology, English, Japanese, Korean, Chinese." },
  { text: "input: Where are the campuses of FPT University located?" },
  { text: "output: Hanoi, Da Nang, Ho Chi Minh City, Can Tho, Quy Nhon." },
  { text: "input: What is the training method of FPT University?" },
  { text: "output: The university emphasizes practical training with modern technology, ensuring good job opportunities for students after graduation." },
  { text: "input: What is the English language requirement at FPT University?" },
  { text: "output: Students must complete 1 year of English study before entering the main program." },
  { text: "input: What is OJT at FPT University?" },
  { text: "output: After the first 5 semesters, students participate in an internship program (OJT) at FPT member companies for 4-8 months." },
  { text: "input: What is the employment rate of FPT University graduates?" },
  { text: "output: 96% of FPT University graduates have jobs after graduation with an average salary of about 8.3 million VND per person per month." },
  { text: "input: Who is the Chairman of the FPT University Council?" },
  { text: "output: Dr. Le Truong Tung." },
  { text: "input: Who is the President of FPT University?" },
  { text: "output: Dr. Nguyen Khac Thanh." },
  { text: "input: Who is the Vice President of FPT University?" },
  { text: "output: Dr. Nguyen Kim Anh, Dr. Nguyen Viet Thang, Dr. Tran Ngoc Tuan, Dr. Nguyen Xuan Phong." },
  { text: "input: What is the composition of the FPT University Council?" },
  { text: "output: The Council consists of Dr. Le Truong Tung (Chairman), Associate Prof. Dr. Truong Gia Binh, Dr. Nguyen Khac Thanh, Dr. Bui Quang Ngoc, Dr. Nguyen Thanh Nam, Dr. Nguyen Kim Anh, MSc. Phan Truong Lam." },
  { text: "input: What qualifications do FPT University lecturers have?" },
  { text: "output: FPT University lecturers include highly qualified individuals, many of whom have studied and worked at prestigious universities around the world." },
  { text: "input: How diverse is the teaching staff at FPT University?" },
  { text: "output: FPT University has a diverse and high-quality teaching staff, with the majority holding postgraduate degrees and many years of teaching experience." },
  { text: "input: Where can detailed information about FPT University lecturers be found?" },
  { text: "output: Detailed information about the lecturers' qualifications, titles, and teaching fields can be found on the official website of FPT University." },
  { text: "input: What is the mission of FPT University?" },
  { text: "output: The mission is to enhance the quality of higher education in Vietnam, emphasizing practical training and technology integration." },
  { text: "input: Who is the Vice Rector responsible for Academic Affairs at FPT University?" },
  { text: "output: Dr. Tran Ngoc Tuan." },
  { text: "input: What is the primary focus of FPT University's training?" },
  { text: "output: Practical experience and modern technology integration." },
  { text: "input: What is the tuition fee for FPT University?" },
  { text: "output: Not provided explicitly in the document." },
  { text: "input: What is the graduation requirement for FPT University students?" },
  { text: "output: Completion of the English language program and participation in OJT." },
  { text: "input: What percentage of FPT University graduates work at FPT Corporation?" },
  { text: "output: 100% have the opportunity to work at FPT after graduation." },
  { text: "input: How does FPT University ensure job opportunities for students?" },
  { text: "output: Through practical training, internships (OJT), and strong connections with the FPT Corporation." },
  { text: "input: What are the roles of the Vice Rectors at FPT University?" },
  { text: "output: They assist the Rector in managing and overseeing various academic and administrative functions of the university." },
  { text: "input: What is the teaching language at FPT University?" },
  { text: "output: Primarily Vietnamese, with some courses taught in English, especially in language departments." },
  { text: "input: Who manages the English language program at FPT University?" },
  { text: "output: Managed by specialized language faculties with experienced instructors." },
  { text: "input: How long is the internship program (OJT) at FPT University?" },
  { text: "output: 4-8 months." },
  { text: "input: What are the benefits of studying at FPT University?" },
  { text: "output: High employability, practical training, opportunities for internships, and strong industry connections." },
  { text: "input: What percentage of FPT University lecturers are international?" },
  { text: "output: A significant number, especially in language programs like English and Japanese." },
  { text: "input: What subjects do international lecturers at FPT University teach?" },
  { text: "output: Subjects such as English and Japanese." },
  { text: "input: What is the role of the Academic Council at FPT University?" },
  { text: "output: To oversee and guide the academic programs, ensuring they meet the university's standards and objectives." },
  { text: "input: How does FPT University integrate technology into its curriculum?" },
  { text: "output: By incorporating modern technology in both teaching methods and course content, preparing students for the demands of the digital age." },
  { text: "input: nhóm làm đồ án FPT societe có mấy người, là những ai" },
]
export default parts



